service: aws-crud-app
provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30


  iam: 
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"
  

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"



plugins:
  - serverless-offline

